In [ ]:
import numpy as np

zer = np.zeros((2,5))
print(zer)
print(zer + 5)
print(zer.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
(2, 5)


In [2]:
matrix = np.random.random((3,3))
print(matrix)
matrix.sort()
print(matrix)

[[0.39502713 0.3887722  0.86333102]
 [0.63708872 0.02246494 0.2305137 ]
 [0.64352422 0.89728876 0.61238634]]
[[0.3887722  0.39502713 0.86333102]
 [0.02246494 0.2305137  0.63708872]
 [0.61238634 0.64352422 0.89728876]]


In [3]:
print(np.random.randint(1, 5, (3,4)))

[[2 1 3 2]
 [1 2 4 3]
 [2 3 4 3]]


In [4]:
x = np.linspace(0,4,10)
print(x)

[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [5]:
print(x.mean(), x.sum(), x.max())

2.0 20.0 4.0


In [6]:
x2 = np.reshape(x, (5, 2))
print(x2)
print(x2.shape)
print(x2.mean())
print(x2.sum())

[[0.         0.44444444]
 [0.88888889 1.33333333]
 [1.77777778 2.22222222]
 [2.66666667 3.11111111]
 [3.55555556 4.        ]]
(5, 2)
2.0
20.0


In [7]:
y = np.linspace(0,4,10).reshape(-1,1)
print(y)

[[0.        ]
 [0.44444444]
 [0.88888889]
 [1.33333333]
 [1.77777778]
 [2.22222222]
 [2.66666667]
 [3.11111111]
 [3.55555556]
 [4.        ]]


In [8]:
print(x @ y) # np.dot(x,y)
print((y**2).sum())

[56.2962963]
56.29629629629629


In [9]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[3 1 4 9 5 7 2 8 6 0]


In [10]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A[:, ::-1]
print(A)
print(B)
B[1][1] = 0
print(A)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 0 6]]


In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A.copy()[:, ::-1]
print(A)
print(B)
B[1][1] = 0
print(A)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


In [16]:
x = np.random.random((2,4))
print(x)
print(x.T)
A = np.array([[1, 2, 3], [4, 5, 6], [4, 5, 6]])
print(np.equal(A, A.T).all())

[[0.20213324 0.35387291 0.48928743 0.46819206]
 [0.90423835 0.46320458 0.55447919 0.85693923]]
[[0.20213324 0.90423835]
 [0.35387291 0.46320458]
 [0.48928743 0.55447919]
 [0.46819206 0.85693923]]
False


In [18]:
def calc_kxb(k,x,b):
    return sum(k*x)+b

k = np.array([1, 5, 10])
b = 3
x = np.array([1,2,3])
calc_kxb(k,x,b)

    

44